[SERVICE]
    Flush              1
    Log_Level          info
    Parsers_File       /fluent-bit/etc/parsers.conf

[INPUT]
    Name               forward
    Listen             0.0.0.0
    Port               24224
    Tag                workshop.*

[FILTER]
    Name               parser
    Match              *
    Key_Name           log
    Parser             json
    Reserve_Data       On
    Preserve_Key       Off

[FILTER]
    Name               record_modifier
    Match              *
    Record             student __STUDENT__

[OUTPUT]
    Name               opensearch
    Match              *
    Host               opensearch
    Port               9200
    Index              observe-__STUDENT__
    Logstash_Format    On
    Logstash_Prefix    observe-__STUDENT__
    Generate_ID        On
    Suppress_Type_Name On
    Replace_Dots       On
    Workers            1
